### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by andrewsomething** [drael/GOnetstat#1]
Hi! I notice that there is no license for this work. Is that intentional or just an oversight? I would be great to clarify that. 

Thanks!

**Comment by drael** [comment]
Hi Andrew, honestly I just forgot to add the license. 
But now that I notice that people are using for other projects, I have just added one.

https://github.com/drael/GOnetstat/commit/a08125f5157d481dd0d0355c021467bd8c84eb6d

**Comment by andrewsomething** [comment]
Thanks so much for clearing that up @drael!
